### ISSUE TITLE
Add link to the YouTube video demonstrating App Deployment use case

### ISSUE THREAD

**Issue by arjuan** [openscore/openscore.github.io#21] opened 2015-01-19 11:50 UTC
It would be great to add a video demonstrating ALL use cases.
But I'd start by adding the video that we already have available at http://youtu.be/3M9mQBOnODA

**Comment by orius123** [comment] 2015-02-16 07:33
Duplicate of #8

**Closed by orius123** 2015-02-16 07:33 UTC
Labels: enhancement
